# NumPy

In [2]:
#numpy liberaries are used to store list type data in the form of array
#arrays can be 1D,2D,3D
#The major difference between Numpy and the list is speed.
#the numpy arrys takes much less space as compared to python lists.
#numpy uses contagious memory.

In [3]:
import numpy as np

# The Basics

In [12]:
a = np.array([1,3,5],dtype= "int64")
#a
print(a)

[1 3 5]


In [6]:
b = np.array([[1,2,3,4,5],[3,4,6,7,8]])
print(b)

[[1 2 3 4 5]
 [3 4 6 7 8]]


In [7]:
a.ndim #note the first code will note execute in jupyter notebook.
b.ndim

2

In [8]:
#Get dimension.
a.ndim

1

In [9]:
#Get Shape
b.shape

(2, 5)

In [16]:
#get type
a.dtype
b.dtype

dtype('int32')

In [13]:
a.itemsize

8

In [15]:
#Get total size
a.nbytes

24

# Accessing/changing specific elements in the rows and columns.

In [17]:
a = np.array([[1,2,4,5,6],[4,6,8,0,7]])


In [21]:
#get specific elements[row ,columns]
a[1,4]
#indexing in numpy starts from 0.

7

In [23]:
#getting entire row.
a[1,:]

array([4, 6, 8, 0, 7])

In [24]:
#getting entire columns.
a[:,3]

array([5, 0])

In [25]:
#Getting bit fancy[startindex:endindex:stepsizea]
a[0,1:6:2] #here 0 represents the row numbers.

array([2, 5])

In [27]:
a[1][3]= 9
a
print(a)

[[1 2 4 5 6]
 [4 6 8 9 7]]


# Initializing different type of arrays.

In [30]:
#All 0s matrix
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
#All 1s matrix
np.ones([2,3], dtype = "int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [34]:
#Any other numbers
np.full([2,2],97)

array([[97, 97],
       [97, 97]])

In [38]:
#Random decimal number matrix
np.random.rand(3,4 )
#note the values gets filled up randomly.

array([[0.67788325, 0.38203756, 0.9241295 , 0.88397839],
       [0.71212665, 0.79781816, 0.44531123, 0.85098562],
       [0.25057173, 0.75530542, 0.93239312, 0.3342785 ]])

In [40]:
#syntax to get random integer values.
np.random.randint(3, size = (3,4))

array([[1, 2, 0, 2],
       [1, 1, 1, 2],
       [0, 2, 1, 0]])

In [41]:
#get identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
#repeating an array
arr = np.array([[2,3,4]])
a = np.repeat(arr,3, axis= 0)#(name of array, no. of repeatation, axis)
print(a)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [ ]:
a = np.ones([5,5])
a

# Copying the arrays


In [53]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [56]:
a = np.array([[1,0,3,4],[2,3,4,5]])
a+2
print(a+2)


[[3 2 5 6]
 [4 5 6 7]]


In [57]:
a//5

array([[0, 0, 0, 0],
       [0, 0, 0, 1]], dtype=int32)

In [63]:
b = np.array([[1,2,3,5],[3,4,5,6]])

In [64]:
a+b

array([[ 2,  2,  6,  9],
       [ 5,  7,  9, 11]])

In [65]:
a*b #numpy matrix multiplication is different from mathematics matrix multiplications.

array([[ 1,  0,  9, 20],
       [ 6, 12, 20, 30]])

In [66]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.95892427],
       [ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ]])

# Linear Algebra

In [67]:
a = np.ones([2,3])
b = np.full([3,2],3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [73]:
d = np.matmul(a,b)
print(d)

[[9. 9.]
 [9. 9.]]


In [71]:
c = np.identity(3)

In [74]:
np.linalg.det(d) #syntax for finding the determinant of the matrix.

0.0

# Statistics using numpy

In [75]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [78]:
np.min(a, axis = 1)

array([1, 3])

In [77]:
np.max(a)

5

In [79]:
np.sum(a)

18

# Reorganizing arrays

In [82]:
a = np.array([[1,2,3],[3,4,5]])
print(a)
#uding reshape functions
b = a.reshape([6,1]) #while reshaping check the total no. of elements of the matrix.
print(b)

[[1 2 3]
 [3 4 5]]
[[1]
 [2]
 [3]
 [3]
 [4]
 [5]]


# Miscellaneous

load data from file

data =  np.genfromtxt('data.txt', delimiter = ',', dtype = "int16")
#no. of elements in each row should be same.

# Advanced Indexing.

In [92]:
data =  np.genfromtxt('data.txt', delimiter = ',', dtype = "int16")
data > 5

array([[False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [93]:
data[data>5]

array([  6,   7,   8,  23,  34,  45,   6, 778,  89,   9], dtype=int16)

In [96]:
#indexing with list using numpy
a = np.array([2,2,3,4,5,6,7,8,8,9])
a[[1,5,7]]

array([2, 6, 8])